### ISSUE TITLE
Upload error occured.

### ISSUE THREAD

**Issue by shawn-chiou** [ChiVincent/youku-ul#1]
Plz help to figure out, thank you.
![image](https://user-images.githubusercontent.com/1298472/58380837-dee1f000-7fe8-11e9-8190-2ddd229f6728.png)

**Comment by ChiVincent** [comment]
Please make sure for `YOUKU_OSS` environment variable is `0` or `false`, it must be set. 

I'll release a version with default value for `YOUKU_OSS`, because youku.com has not implemented this feature yet.

**Comment by ChiVincent** [comment]
[1.0.5](https://github.com/ChiVincent/youku-ul/releases/tag/1.0.5) was released, can use `composer update` for latest version.
