### ISSUE TITLE
UploadExceptions: Can fill in the 80 most title characters

### ISSUE THREAD

**Issue by shawn-chiou** [ChiVincent/youku-ul#2]
Plz help to figure it out, thanks.

![image](https://user-images.githubusercontent.com/1298472/58539848-c234fa80-822a-11e9-9896-8fdf1d017249.png)

**Comment by ChiVincent** [comment]
This is the limit by youku.com, **title** (it is filename in this repository) cannot larger than 60 bytes.

See [Client Uploading](https://cloud.youku.com/docs?id=111) for more information.
