### ISSUE TITLE
Error occured when uploading.

### ISSUE THREAD

**Issue by shawn-chiou** [ChiVincent/youku-ul#3]
Plz help to figure out why uploading failed. All failed. Thank you.

![image](https://user-images.githubusercontent.com/1298472/58768588-565ae500-85d0-11e9-913f-68d6043a6119.png)

**Comment by ChiVincent** [comment]
This is a beta version error, please use the version `1.0.6` temporarily.

**Comment by shawn-chiou** [comment]
I checked out 1.0.6 and increase allowed memory to 6G, but still got some errors. Plz help to figure out again. Thanks.

![image](https://user-images.githubusercontent.com/1298472/58813071-a039de80-8655-11e9-90cb-78be0ba4c39f.png)

**Comment by ChiVincent** [comment]
Parameter type error is fixed in 1.0.7. 

The issue of "connection reset by peer" maybe CA cert is invalid or the peer is unavailable.
